//@ts-nocheck
export const CustomProfile = {
    "name": "Privet",
    "label": "Manufacturing (my profile)",
    "description": "Default Autodesk settings",
    "storageVersion": "2.0",
    "persistent": [
        "alwaysUsePivot",
        "zoomTowardsPivot",
        "reverseHorizontalLookDirection",
        "reverseVerticalLookDirection",
        "orbitPastWorldPoles",
        "clickToSetCOI",
        "ghosting",
        "optimizeNavigation",
        "ambientShadows",
        "antialiasing",
        "groundShadow",
        "groundReflection",
        "firstPersonToolPopup",
        "bimWalkToolPopup",
        "bimWalkGravity",
        "viewType",
        "selectionMode",
        "swapBlackAndWhite",
        "loadingAnimation",
        "openPropertiesOnSelect",
        "reverseMouseZoomDir",
        "leftHandedMouseSetup",
        "wheelSetsPivot",
        "keyMapCmd",
        "displayUnits",
        "displayUnitsPrecision"
    ],
    "settings": {
        "ambientShadows": false,
        "antialiasing": true,
        "groundShadow": false,
        "groundReflection": false,
        "ghosting": false,
        "viewCube": true,
        "viewCubeCompass": false,
        "viewType": 0,
        "lineRendering": true, // !!!
        "lightPreset": 1,
        "edgeRendering": true,
        "reverseHorizontalLookDirection": false,
        "reverseVerticalLookDirection": false,
        "alwaysUsePivot": false,
        "zoomTowardsPivot": false,
        "orbitPastWorldPoles": true,
        "clickToSetCOI": false,
        "optimizeNavigation": false,
        "envMapBackground": false,
        "firstPersonToolPopup": true,
        "bimWalkToolPopup": true,
        "bimWalkNavigatorType": "default",
        "bimWalkGravity": true,
        "defaultNavigationTool3D": "default",
        "selectionMode": 0,
        "enableCustomOrbitToolCursor": true,
        "explodeStrategy": "hierarchy",
        "selectionSetsPivot": false,
        "forceDoubleSided": false,
        "displaySectionHatches": true,
        "grayscale": false,
        "swapBlackAndWhite": false,
        "loadingAnimation": true,
        "forcePDFCalibration": false,
        "forceLeafletCalibration": true,
        "disablePdfHighlight": false,
        "usePdfViewportInfo": true,
        "progressiveRendering": true,
        "openPropertiesOnSelect": false,
        "pointRendering": true,
        "backgroundColorPreset": false,
        "reverseMouseZoomDir": true,
        "leftHandedMouseSetup": false,
        "fusionOrbit": true,
        "fusionOrbitConstrained": true,
        "wheelSetsPivot": false,
        "restoreMeasurements": true,
        "displayUnits": 'mm',
        "displayUnitsPrecision": 2,
        "keyMapCmd": true
    },
    "extensions": {
        "load": [],
        "unload": []
    }
}