/* tslint:disable */
/* eslint-disable */
/**
 * Mymount
 * Mymount
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     * @type {number}
     * @memberof Comment
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    page: string;
    /**
     * 
     * @type {Date}
     * @memberof Comment
     */
    readonly time: Date;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    text: string;
    /**
     * 
     * @type {number}
     * @memberof Comment
     */
    parent?: number;
    /**
     * 
     * @type {number}
     * @memberof Comment
     */
    user?: number;
    /**
     * 
     * @type {number}
     * @memberof Comment
     */
    likes?: number;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    media?: string;
}

/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): boolean {
    if (!('page' in value)) return false;
    if (!('time' in value)) return false;
    if (!('text' in value)) return false;
    return true;
}

export function CommentFromJSON(json: any): Comment {
    return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'page': json['page'],
        'time': (new Date(json['time'])),
        'text': json['text'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'user': json['user'] == null ? undefined : json['user'],
        'likes': json['likes'] == null ? undefined : json['likes'],
        'media': json['media'] == null ? undefined : json['media'],
    };
}

export function CommentToJSON(value?: Comment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'page': value['page'],
        'text': value['text'],
        'parent': value['parent'],
        'user': value['user'],
        'likes': value['likes'],
        'media': value['media'],
    };
}

