/* tslint:disable */
/* eslint-disable */
/**
 * Mymount
 * Mymount
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedStatus
 */
export interface PatchedStatus {
    /**
     * 
     * @type {number}
     * @memberof PatchedStatus
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedStatus
     */
    step?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedStatus
     */
    substep?: string;
}

/**
 * Check if a given object implements the PatchedStatus interface.
 */
export function instanceOfPatchedStatus(value: object): boolean {
    return true;
}

export function PatchedStatusFromJSON(json: any): PatchedStatus {
    return PatchedStatusFromJSONTyped(json, false);
}

export function PatchedStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'step': json['step'] == null ? undefined : json['step'],
        'substep': json['substep'] == null ? undefined : json['substep'],
    };
}

export function PatchedStatusToJSON(value?: PatchedStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'step': value['step'],
        'substep': value['substep'],
    };
}

