/* tslint:disable */
/* eslint-disable */
/**
 * Mymount
 * Mymount
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedComment
 */
export interface PatchedComment {
    /**
     * 
     * @type {number}
     * @memberof PatchedComment
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedComment
     */
    page?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedComment
     */
    readonly time?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedComment
     */
    text?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedComment
     */
    parent?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedComment
     */
    user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedComment
     */
    likes?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedComment
     */
    media?: string;
}

/**
 * Check if a given object implements the PatchedComment interface.
 */
export function instanceOfPatchedComment(value: object): boolean {
    return true;
}

export function PatchedCommentFromJSON(json: any): PatchedComment {
    return PatchedCommentFromJSONTyped(json, false);
}

export function PatchedCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedComment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'page': json['page'] == null ? undefined : json['page'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'text': json['text'] == null ? undefined : json['text'],
        'parent': json['parent'] == null ? undefined : json['parent'],
        'user': json['user'] == null ? undefined : json['user'],
        'likes': json['likes'] == null ? undefined : json['likes'],
        'media': json['media'] == null ? undefined : json['media'],
    };
}

export function PatchedCommentToJSON(value?: PatchedComment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'page': value['page'],
        'text': value['text'],
        'parent': value['parent'],
        'user': value['user'],
        'likes': value['likes'],
        'media': value['media'],
    };
}

