/* tslint:disable */
/* eslint-disable */
/**
 * Mymount
 * Mymount
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Shop
 */
export interface Shop {
    /**
     * 
     * @type {number}
     * @memberof Shop
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Shop
     */
    page?: string;
    /**
     * 
     * @type {string}
     * @memberof Shop
     */
    media?: string;
    /**
     * 
     * @type {number}
     * @memberof Shop
     */
    viewId?: number;
    /**
     * 
     * @type {string}
     * @memberof Shop
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Shop
     */
    summary?: string;
    /**
     * 
     * @type {number}
     * @memberof Shop
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof Shop
     */
    productType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Shop
     */
    inStock?: boolean;
}

/**
 * Check if a given object implements the Shop interface.
 */
export function instanceOfShop(value: object): boolean {
    if (!('id' in value)) return false;
    return true;
}

export function ShopFromJSON(json: any): Shop {
    return ShopFromJSONTyped(json, false);
}

export function ShopFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shop {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'page': json['page'] == null ? undefined : json['page'],
        'media': json['media'] == null ? undefined : json['media'],
        'viewId': json['viewId'] == null ? undefined : json['viewId'],
        'name': json['name'] == null ? undefined : json['name'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'price': json['price'] == null ? undefined : json['price'],
        'productType': json['productType'] == null ? undefined : json['productType'],
        'inStock': json['inStock'] == null ? undefined : json['inStock'],
    };
}

export function ShopToJSON(value?: Shop | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'media': value['media'],
        'viewId': value['viewId'],
        'name': value['name'],
        'summary': value['summary'],
        'price': value['price'],
        'productType': value['productType'],
        'inStock': value['inStock'],
    };
}

