/* tslint:disable */
/* eslint-disable */
/**
 * Mymount
 * Mymount
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Gallery
 */
export interface Gallery {
    /**
     * 
     * @type {number}
     * @memberof Gallery
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Gallery
     */
    media?: string;
    /**
     * 
     * @type {number}
     * @memberof Gallery
     */
    viewId?: number;
    /**
     * 
     * @type {string}
     * @memberof Gallery
     */
    mediaTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof Gallery
     */
    mediaText?: string;
}

/**
 * Check if a given object implements the Gallery interface.
 */
export function instanceOfGallery(value: object): boolean {
    if (!('id' in value)) return false;
    return true;
}

export function GalleryFromJSON(json: any): Gallery {
    return GalleryFromJSONTyped(json, false);
}

export function GalleryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Gallery {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'media': json['media'] == null ? undefined : json['media'],
        'viewId': json['viewId'] == null ? undefined : json['viewId'],
        'mediaTitle': json['mediaTitle'] == null ? undefined : json['mediaTitle'],
        'mediaText': json['mediaText'] == null ? undefined : json['mediaText'],
    };
}

export function GalleryToJSON(value?: Gallery | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'media': value['media'],
        'viewId': value['viewId'],
        'mediaTitle': value['mediaTitle'],
        'mediaText': value['mediaText'],
    };
}

