/* tslint:disable */
/* eslint-disable */
/**
 * Mymount
 * Mymount
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Gallery } from './Gallery';
import {
    GalleryFromJSON,
    GalleryFromJSONTyped,
    GalleryToJSON,
} from './Gallery';

/**
 * 
 * @export
 * @interface PaginatedGalleryList
 */
export interface PaginatedGalleryList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedGalleryList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedGalleryList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedGalleryList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Gallery>}
     * @memberof PaginatedGalleryList
     */
    results: Array<Gallery>;
}

/**
 * Check if a given object implements the PaginatedGalleryList interface.
 */
export function instanceOfPaginatedGalleryList(value: object): boolean {
    if (!('count' in value)) return false;
    if (!('results' in value)) return false;
    return true;
}

export function PaginatedGalleryListFromJSON(json: any): PaginatedGalleryList {
    return PaginatedGalleryListFromJSONTyped(json, false);
}

export function PaginatedGalleryListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedGalleryList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(GalleryFromJSON)),
    };
}

export function PaginatedGalleryListToJSON(value?: PaginatedGalleryList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(GalleryToJSON)),
    };
}

