/* tslint:disable */
/* eslint-disable */
/**
 * Mymount
 * Mymount
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * 
 * @export
 * @interface PaginatedProductList
 */
export interface PaginatedProductList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProductList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProductList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Product>}
     * @memberof PaginatedProductList
     */
    results: Array<Product>;
}

/**
 * Check if a given object implements the PaginatedProductList interface.
 */
export function instanceOfPaginatedProductList(value: object): boolean {
    if (!('count' in value)) return false;
    if (!('results' in value)) return false;
    return true;
}

export function PaginatedProductListFromJSON(json: any): PaginatedProductList {
    return PaginatedProductListFromJSONTyped(json, false);
}

export function PaginatedProductListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedProductList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ProductFromJSON)),
    };
}

export function PaginatedProductListToJSON(value?: PaginatedProductList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ProductToJSON)),
    };
}

