/* tslint:disable */
/* eslint-disable */
/**
 * Mymount
 * Mymount
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
} from './Order';

/**
 * 
 * @export
 * @interface PaginatedOrderList
 */
export interface PaginatedOrderList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedOrderList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedOrderList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedOrderList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Order>}
     * @memberof PaginatedOrderList
     */
    results: Array<Order>;
}

/**
 * Check if a given object implements the PaginatedOrderList interface.
 */
export function instanceOfPaginatedOrderList(value: object): boolean {
    if (!('count' in value)) return false;
    if (!('results' in value)) return false;
    return true;
}

export function PaginatedOrderListFromJSON(json: any): PaginatedOrderList {
    return PaginatedOrderListFromJSONTyped(json, false);
}

export function PaginatedOrderListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedOrderList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(OrderFromJSON)),
    };
}

export function PaginatedOrderListToJSON(value?: PaginatedOrderList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(OrderToJSON)),
    };
}

