/* tslint:disable */
/* eslint-disable */
/**
 * Mymount
 * Mymount
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUser
 */
export interface PatchedUser {
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    messageToken?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    email?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedUser
     */
    telegramId?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    deliveryName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    deliverySurname?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    deliveryLastname?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    deliveryPhone?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUser
     */
    deliveryAddress?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    notificationEmail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    notificationTelegram?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedUser
     */
    notificationPush?: boolean;
}

/**
 * Check if a given object implements the PatchedUser interface.
 */
export function instanceOfPatchedUser(value: object): boolean {
    return true;
}

export function PatchedUserFromJSON(json: any): PatchedUser {
    return PatchedUserFromJSONTyped(json, false);
}

export function PatchedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUser {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'messageToken': json['messageToken'] == null ? undefined : json['messageToken'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'telegramId': json['telegramId'] == null ? undefined : json['telegramId'],
        'deliveryName': json['deliveryName'] == null ? undefined : json['deliveryName'],
        'deliverySurname': json['deliverySurname'] == null ? undefined : json['deliverySurname'],
        'deliveryLastname': json['deliveryLastname'] == null ? undefined : json['deliveryLastname'],
        'deliveryPhone': json['deliveryPhone'] == null ? undefined : json['deliveryPhone'],
        'deliveryAddress': json['deliveryAddress'] == null ? undefined : json['deliveryAddress'],
        'notificationEmail': json['notificationEmail'] == null ? undefined : json['notificationEmail'],
        'notificationTelegram': json['notificationTelegram'] == null ? undefined : json['notificationTelegram'],
        'notificationPush': json['notificationPush'] == null ? undefined : json['notificationPush'],
    };
}

export function PatchedUserToJSON(value?: PatchedUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'uuid': value['uuid'],
        'messageToken': value['messageToken'],
        'name': value['name'],
        'email': value['email'],
        'telegramId': value['telegramId'],
        'deliveryName': value['deliveryName'],
        'deliverySurname': value['deliverySurname'],
        'deliveryLastname': value['deliveryLastname'],
        'deliveryPhone': value['deliveryPhone'],
        'deliveryAddress': value['deliveryAddress'],
        'notificationEmail': value['notificationEmail'],
        'notificationTelegram': value['notificationTelegram'],
        'notificationPush': value['notificationPush'],
    };
}

