/* tslint:disable */
/* eslint-disable */
/**
 * Mymount
 * Mymount
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * 
 * @export
 * @interface PatchedShop
 */
export interface PatchedShop {
    /**
     * 
     * @type {number}
     * @memberof PatchedShop
     */
    readonly id?: number;
    /**
     * 
     * @type {Product}
     * @memberof PatchedShop
     */
    readonly product?: Product;
    /**
     * 
     * @type {number}
     * @memberof PatchedShop
     */
    viewId?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedShop
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedShop
     */
    description?: string;
}

/**
 * Check if a given object implements the PatchedShop interface.
 */
export function instanceOfPatchedShop(value: object): boolean {
    return true;
}

export function PatchedShopFromJSON(json: any): PatchedShop {
    return PatchedShopFromJSONTyped(json, false);
}

export function PatchedShopFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedShop {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'product': json['product'] == null ? undefined : ProductFromJSON(json['product']),
        'viewId': json['viewId'] == null ? undefined : json['viewId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function PatchedShopToJSON(value?: PatchedShop | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'viewId': value['viewId'],
        'title': value['title'],
        'description': value['description'],
    };
}

