/* tslint:disable */
/* eslint-disable */
/**
 * Mymount
 * Mymount
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * 
 * @export
 * @interface Shop
 */
export interface Shop {
    /**
     * 
     * @type {number}
     * @memberof Shop
     */
    readonly id: number;
    /**
     * 
     * @type {Product}
     * @memberof Shop
     */
    readonly product: Product;
    /**
     * 
     * @type {number}
     * @memberof Shop
     */
    viewId?: number;
    /**
     * 
     * @type {string}
     * @memberof Shop
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Shop
     */
    description?: string;
}

/**
 * Check if a given object implements the Shop interface.
 */
export function instanceOfShop(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('product' in value)) return false;
    return true;
}

export function ShopFromJSON(json: any): Shop {
    return ShopFromJSONTyped(json, false);
}

export function ShopFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shop {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'product': ProductFromJSON(json['product']),
        'viewId': json['viewId'] == null ? undefined : json['viewId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ShopToJSON(value?: Shop | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'viewId': value['viewId'],
        'title': value['title'],
        'description': value['description'],
    };
}

